### ISSUE TITLE
Importing crashes unity

### ISSUE THREAD

**Issue by defc0n1** [pixyz-software/plugin-unity-samples#1]
Importing https://gitlab.com/pixyz_co/support/plugin-unity/plugin-unity-samples/-/raw/releases/PixyzPluginUnity-Samples-2020.1.unitypackage crashes Unity version 2019.3.12f1 and renders the installation unusable

**Comment by ogxd** [comment]
Could you try with this package instead ?
https://github.com/pixyz-software/plugin-unity-samples/releases/download/2020.1/PixyzPluginUnity-Samples-2020.1.unitypackage

It looks like the link in the readme points to a corrupted package.

**Comment by juggernate** [comment]
> Could you try with this package instead ?
> https://github.com/pixyz-software/plugin-unity-samples/releases/download/2020.1/PixyzPluginUnity-Samples-2020.1.unitypackage
> 
> It looks like the link in the readme points to a corrupted package.

This link is 404. Was the release deleted?

**Comment by ogxd** [comment]
Sorry about that, could you try gain please ? Same link

**Comment by juggernate** [comment]
That works and imports without crash. Thanks!
